### ISSUE TITLE
Error with download modules

### ISSUE THREAD

**Issue by IvanKorotchenko** [LimerBoy/hackpy#2]
My code:
`import hackpy 

hackpy.load_modules(
    'autorun.exe',      
    'webcam.exe',       
    'nircmd.exe',       
    'activity.exe',     
    'audio.zip',        
    'bsod.exe',         
    'rotate_screen.exe',
    'uac.exe',         
    'watchdog.exe',    
    'system_status.exe') 
` 

This error show up when I start code:
` Traceback (most recent call last):
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hackpy\modules.py", line 37, in load_module
    download(server_url + module, output = location)
NameError: name 'download' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MSI\Documents\Python Scripts\stiler\main.py", line 18, in <module>
    'system_status.exe' # Size: 16.0 KB | Need for hackpy.inSandBox(), hackpy.inVirtualBox(), hackpy.cpuName(), hackpy.cpuUsage(), hackpy.gpuName(), hackpy.totalMemory()
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hackpy\modules.py", line 57, in load_modules
    load_module(module)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hackpy\modules.py", line 39, in load_module
    raise ConnectionError('Failed connect to server while downloading module ' + module)
ConnectionError: Failed connect to server while downloading module autorun.exe`

What should I do?

**Comment by LimerBoy** [comment]
Try to remove autorun.exe from hackpy.load_modules()
I am not updating this module anymore, try my **Inferno**
github.com/LimerBoy/Inferno
